name: Fetch News

on:
  push:
    branches:
      - main  # Run on push to main branch
      - master  # Run on push to master branch (if you use master)
  schedule:
    # Run daily at 6 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    environment: SUPABASE_URL
    
    # Add permissions to allow pushing to the repository
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Use 3.8 for better compatibility
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}-v2
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}-
          ${{ runner.os }}-pip-v2-
          ${{ runner.os }}-pip-
    
    - name: Cache NLTK data
      uses: actions/cache@v3
      with:
        path: ~/nltk_data
        key: ${{ runner.os }}-nltk-data-v1
        restore-keys: |
          ${{ runner.os }}-nltk-data-
    
    - name: Cache Chrome and WebDriver
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/selenium
          ~/.wdm
        key: ${{ runner.os }}-chrome-webdriver-v1
        restore-keys: |
          ${{ runner.os }}-chrome-webdriver-
    
    - name: Install dependencies
      run: |
        # Show Python and pip versions for debugging
        python --version
        pip --version
        
        # Upgrade pip and install wheel for faster builds
        pip install --upgrade pip wheel
        
        # Install all dependencies from requirements file
        echo "Installing dependencies from requirements.txt..."
        pip install -r requirements.txt
        
        # Download NLTK data (will be cached)
        python -c "
        import nltk
        import os
        nltk_data_dir = os.path.expanduser('~/nltk_data')
        if not os.path.exists(os.path.join(nltk_data_dir, 'tokenizers', 'punkt')):
            print('Downloading NLTK punkt data...')
            nltk.download('punkt', download_dir=nltk_data_dir)
        else:
            print('NLTK punkt data already cached')
        "
        
        # Verify key imports work
        python -c "
        try:
            import pygooglenews
            import selenium
            import nltk
            print('SUCCESS: All key dependencies imported successfully')
        except ImportError as e:
            print(f'ERROR: Import error: {e}')
            exit(1)
        "
        
        # List installed packages for debugging (only show key ones)
        echo "Key installed packages:"
        pip list | grep -E "(selenium|nltk|newspaper|pygooglenews|webdriver-manager)" || echo "Package listing completed"
    
    - name: Verify installation
      run: |
        python -c "import pygooglenews; print('PyGoogleNews imported successfully')"
        python -c "from pygooglenews import GoogleNews; print('Successfully imported GoogleNews')"
        python -c "import fastapi; print('FastAPI imported successfully')"
    
    - name: Run installation test script
      run: |
        if [ -f scripts/test_installation.py ]; then
          python scripts/test_installation.py
        fi
    
    - name: Fetch top news (scheduled)
      if: github.event_name == 'schedule'
      run: |
        # Create data directory if it doesn't exist
        mkdir -p data
        # General news categories
        python scripts/fetch_news.py --type top --output data/news_top.json
        python scripts/fetch_news.py --type topic --topic technology --output data/news_tech.json
        python scripts/fetch_news.py --type topic --topic business --output data/news_business.json
        # Additional categories like Inshorts
        python scripts/fetch_news.py --type topic --topic entertainment --output data/news_entertainment.json
        python scripts/fetch_news.py --type topic --topic sports --output data/news_sports.json
        python scripts/fetch_news.py --type topic --topic science --output data/news_science.json
        python scripts/fetch_news.py --type topic --topic health --output data/news_health.json
        python scripts/fetch_news.py --type topic --topic world --output data/news_world.json
        # Trending topics
        python scripts/fetch_news.py --type search --query "trending" --when 1d --output data/news_trending.json
    
    - name: Run complete news workflow (manual)
      if: github.event_name == 'workflow_dispatch'
      run: |
        # Run the complete workflow as defined in main.py
        python main.py --headless
    
    - name: Fetch news (push trigger)
      if: github.event_name == 'push'
      run: |
        # Create data directory if it doesn't exist
        mkdir -p data
        # General news categories
        python scripts/fetch_news.py --type top --output data/news_top.json
        python scripts/fetch_news.py --type topic --topic technology --output data/news_tech.json
        python scripts/fetch_news.py --type topic --topic business --output data/news_business.json
        # Additional categories like Inshorts
        python scripts/fetch_news.py --type topic --topic entertainment --output data/news_entertainment.json
        python scripts/fetch_news.py --type topic --topic sports --output data/news_sports.json
        python scripts/fetch_news.py --type topic --topic science --output data/news_science.json
        python scripts/fetch_news.py --type topic --topic health --output data/news_health.json
        python scripts/fetch_news.py --type topic --topic world --output data/news_world.json
        # Trending topics
        python scripts/fetch_news.py --type search --query "trending" --when 1d --output data/news_trending.json
    
    - name: Set up Chrome for Selenium
      if: github.event_name == 'push' || github.event_name == 'schedule'
      run: |
        # Check if Chrome is already installed
        if command -v google-chrome &> /dev/null; then
          echo "Chrome already installed: $(google-chrome --version)"
        else
          echo "Installing Chrome for Selenium..."
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "Chrome installed: $(google-chrome --version)"
        fi
    
    - name: Generate Inshorts-style news
      if: github.event_name == 'push' || github.event_name == 'schedule'
      run: |
        # Check if news files exist
        echo "Checking for news files..."
        ls -la data/
        
        # Generate Inshorts-style summaries for all news categories using shared browser
        echo "Generating Inshorts summaries for all categories with shared browser optimization..."
        python scripts/generate_all_inshorts.py --input-dir data --output-dir data --max-articles 15 --headless
        
        # List generated files
        echo "Generated Inshorts files:"
        ls -la data/inshorts_* 2>/dev/null || echo "No inshorts files generated yet"
    
    - name: Push to Supabase
      if: github.event_name == 'push' || github.event_name == 'schedule'
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        # Check if inshorts files were generated
        echo "Checking for generated inshorts files..."
        if ls data/inshorts_*.json 1> /dev/null 2>&1; then
          echo "Found inshorts files, proceeding with Supabase upload..."
          
          # Push all inshorts data to Supabase
          echo "Uploading inshorts data to Supabase..."
          python scripts/push_inshorts_to_supabase.py
          
          echo "Supabase upload completed!"
        else
          echo "No inshorts files found, skipping Supabase upload"
        fi
    
    - name: Commit and push changes
      if: success() # Only run if previous steps succeeded
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update news data - $(date)"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        fi